[build-system]
requires = ["setuptools>=82.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "py-wraps-data-types"
version = "0.1.0"
description = "Foundational data types and schemas for scalable Python wrappers."
requires-python = ">=3.14"
dependencies = []
